/** JSON output schema hints per agent slug — passed to LLM for structured responses. */
export const OUTPUT_SCHEMAS: Record<string, object> = {
  'keyword-research': {
    executive_summary: '',
    client_context_used: [],
    keyword_clusters: [
      {
        cluster_name: '',
        intent: '',
        funnel_stage: '',
        primary_keywords: [],
        secondary_keywords: [],
        near_me_keywords: [],
        aeo_questions: [],
        geo_prompts: [],
        recommended_page: '',
        priority: 0,
        difficulty: '',
        confidence: 'AI Estimated',
      },
    ],
    page_mapping: [],
    internal_linking_plan: [],
    schema_recommendations: [],
    content_opportunities: [],
    risks: [],
    next_actions: [],
  },
  'content-seo': {
    topical_map: [],
    pillar_pages: [],
    service_pages: [],
    city_pages: [],
    blog_clusters: [],
    entities: [],
    eav_structure: [],
    semantic_terms: [],
    heading_structure: [],
    faq_blocks: [],
    snippet_blocks: [],
    internal_links: [],
    schema: [],
    cta_plan: [],
    quality_notes: [],
  },
  'local-seo': {
    gbp_categories: [],
    services: [],
    service_areas: [],
    description: '',
    posts: [],
    qa: [],
    photo_plan: [],
    review_plan: [],
    citation_plan: [],
    local_pages: [],
    local_entity_signals: [],
    risk_flags: [],
    next_actions: [],
  },
  'technical-seo': {
    crawl_issues: [],
    indexation_issues: [],
    metadata_issues: [],
    schema_issues: [],
    performance_issues: [],
    mobile_issues: [],
    internal_link_issues: [],
    priority_fixes: [],
    developer_instructions: [],
    qa_checklist: [],
  },
  manager: {
    client_summary: '',
    business_model: '',
    location_service_scope: '',
    primary_growth_objective: '',
    immediate_risks: [],
    task_sequence: [],
    agent_assignment_plan: [],
    expected_outputs: [],
    roadmap_30_60_90: { days_30: [], days_60: [], days_90: [] },
    qa_checklist: [],
  },
  'competitor-research': {
    direct_competitors: [],
    local_pack_competitors: [],
    organic_competitors: [],
    weak_points: [],
    strong_points: [],
    ranking_gaps: [],
    content_gaps: [],
    opportunity_score: 0,
    action_plan: [],
    validation_tools_needed: [],
  },
  'ai-visibility': {
    ai_overview_targets: [],
    answer_ready_sections: [],
    faq_schema: [],
    conversational_queries: [],
    paa_targets: [],
    geo_retrieval_angles: [],
    entity_disambiguation: [],
    local_answer_blocks: [],
    next_actions: [],
  },
};

export function getOutputSchemaHint(slug: string): string | undefined {
  const schema = OUTPUT_SCHEMAS[slug];
  return schema ? JSON.stringify(schema, null, 2) : undefined;
}

export function getDefaultOutputSchema(): object {
  return {
    executive_summary: '',
    client_context_used: [],
    key_findings: [],
    strategic_recommendation: '',
    tactical_execution: [],
    priority_ranking: [],
    internal_linking_plan: [],
    schema_plan: [],
    aeo_geo_plan: [],
    cro_plan: [],
    risks: [],
    missing_data: [],
    next_7_days: [],
    next_30_days: [],
    qa_checklist: [],
  };
}
