/** Valiant Firm SEO Master workbook tab specifications. */

export interface WorkbookTabSpec {
  name: string;
  columns: string[];
  minRows: number;
}

export const VF_WORKBOOK_TABS: WorkbookTabSpec[] = [
  { name: 'Executive Dashboard', columns: ['Section', 'Metric', 'Value', 'Notes'], minRows: 25 },
  {
    name: 'Source Evidence',
    columns: [
      'Evidence ID',
      'Data Point',
      'Source Type',
      'Source Name',
      'Source URL',
      'Tool Used',
      'Date Checked',
      'Screenshot/File Reference',
      'Confidence Level',
      'Validation Status',
      'Notes',
    ],
    minRows: 10,
  },
  {
    name: 'Validation Notes',
    columns: ['Assumption', 'Why It Was Used', 'Risk Level', 'Validation Needed', 'Recommended Tool', 'Priority'],
    minRows: 5,
  },
  {
    name: 'Market Grouping',
    columns: [
      'Market Code',
      'Market Name',
      'Core City',
      'Supporting Cities',
      'County/Region',
      'State',
      'Distance from Main Location',
      'Local SEO Difficulty',
      'Opportunity Score',
      'Priority Tier',
      'Recommended Strategy',
      'Required Pages',
      'GBP Relevance Notes',
      'Risk Notes',
    ],
    minRows: 3,
  },
  {
    name: 'Master Keywords',
    columns: [
      'Keyword',
      'Keyword Type',
      'Service',
      'Location',
      'Market',
      'Search Intent',
      'Funnel Stage',
      'Priority',
      'Estimated Volume',
      'Estimated CPC',
      'Estimated Difficulty',
      'Commercial Intent Score',
      'Local Intent Score',
      'AEO Potential',
      'GEO Potential',
      'Recommended Page',
      'Current URL',
      'New URL Needed',
      'Validation Status',
      'Source',
      'Notes',
    ],
    minRows: 30,
  },
  {
    name: 'Near Me Keywords',
    columns: [
      'Near Me Keyword',
      'Service',
      'Location',
      'Market',
      'Search Intent',
      'Landing Page',
      'Local Pack Relevance',
      'GBP Relevance',
      'Priority',
      'Confidence',
      'Notes',
    ],
    minRows: 15,
  },
  {
    name: 'Competitor Matrix',
    columns: [
      'Competitor Name',
      'Website',
      'Location',
      'Market',
      'Competitor Type',
      'Organic Competitor',
      'Local Pack Competitor',
      'GBP Competitor',
      'Content Competitor',
      'Estimated DA/DR',
      'Estimated Organic Traffic',
      'Estimated Ranking Keywords',
      'Review Count',
      'Review Rating',
      'Services Offered',
      'Strong Pages',
      'Weak Pages',
      'Content Gaps',
      'GBP Gaps',
      'Schema Gaps',
      'Backlink Gaps',
      'CRO Gaps',
      'Threat Level',
      'Opportunity Notes',
      'Validation Status',
      'Source URL',
    ],
    minRows: 5,
  },
  {
    name: 'Competitor Weak Points',
    columns: [
      'Competitor',
      'Weak Point',
      'Category',
      'Evidence',
      'How We Can Beat Them',
      'Priority',
      'Page/Asset Needed',
      'Validation Status',
    ],
    minRows: 8,
  },
  {
    name: 'Website Audit',
    columns: [
      'URL',
      'Page Type',
      'Title',
      'Meta Description',
      'H1',
      'Word Count',
      'Indexability',
      'Canonical',
      'Status Code',
      'Schema Present',
      'Internal Links',
      'CTA Present',
      'Image ALT',
      'Speed Risk',
      'Content Quality',
      'Duplicate Risk',
      'Issue',
      'Priority',
      'Fix Recommendation',
      'Developer Notes',
      'Validation Status',
    ],
    minRows: 5,
  },
  {
    name: 'Website Gap Analysis',
    columns: [
      'Gap Type',
      'Missing Page/Asset',
      'Target Keyword',
      'Target Location',
      'Current Problem',
      'SEO Impact',
      'CRO Impact',
      'Priority',
      'Recommended URL',
      'Required Content',
      'Internal Links Needed',
      'Schema Needed',
      'Notes',
    ],
    minRows: 10,
  },
  {
    name: 'Website Architecture',
    columns: [
      'Page ID',
      'Page Type',
      'Page Title',
      'URL Slug',
      'Parent Page',
      'Target Keyword',
      'Secondary Keywords',
      'Market',
      'Funnel Stage',
      'Search Intent',
      'CTA',
      'Word Count Target',
      'Schema Type',
      'Internal Links In',
      'Internal Links Out',
      'Priority',
      'Status',
    ],
    minRows: 10,
  },
  {
    name: 'Service Pages',
    columns: [
      'Service',
      'Target Keyword',
      'URL',
      'Supporting Keywords',
      'Pain Points',
      'Conversion Angle',
      'Required Sections',
      'FAQ Questions',
      'Schema',
      'Internal Links',
      'CTA',
      'Priority',
    ],
    minRows: 5,
  },
  {
    name: 'City Location Pages',
    columns: [
      'City',
      'Market',
      'County',
      'State',
      'Target Keyword',
      'URL',
      'Local Proof Needed',
      'Nearby Areas',
      'Service Mentions',
      'Internal Links',
      'GBP Support',
      'Review Angle',
      'CTA',
      'Risk Notes',
      'Priority',
    ],
    minRows: 5,
  },
  {
    name: 'Blog Calendar',
    columns: [
      'Month',
      'Topic',
      'Target Keyword',
      'Search Intent',
      'Funnel Stage',
      'Related Service',
      'Related Location',
      'AEO Question',
      'GEO Prompt',
      'Internal Links',
      'CTA',
      'Content Brief Needed',
      'Priority',
      'Status',
    ],
    minRows: 12,
  },
  {
    name: 'AEO GEO AI Visibility',
    columns: [
      'Query',
      'Query Type',
      'User Intent',
      'Recommended Answer Block',
      'Target Page',
      'Entity Mentioned',
      'Source-Worthy Data Needed',
      'FAQ Schema Needed',
      'AI Overview Potential',
      'ChatGPT Retrieval Potential',
      'Perplexity Retrieval Potential',
      'Gemini Retrieval Potential',
      'Priority',
      'Notes',
    ],
    minRows: 15,
  },
  {
    name: 'Entity SEO Map',
    columns: [
      'Entity',
      'Entity Type',
      'Attributes',
      'Values',
      'Related Services',
      'Related Locations',
      'Page Target',
      'Schema Type',
      'Internal Link Target',
      'E-E-A-T Support',
      'Notes',
    ],
    minRows: 8,
  },
  {
    name: 'Semantic SEO Topical Map',
    columns: [
      'Topic Cluster',
      'Parent Entity',
      'Subtopic',
      'Keyword Examples',
      'User Intent',
      'Required Page',
      'Supporting Content',
      'Internal Links',
      'Information Gain Opportunity',
      'Priority',
    ],
    minRows: 10,
  },
  {
    name: 'Internal Linking Map',
    columns: ['Source Page', 'Target Page', 'Anchor Text', 'Link Type', 'Context', 'Reason', 'Priority', 'Status'],
    minRows: 15,
  },
  {
    name: 'Schema Strategy',
    columns: [
      'Page',
      'URL',
      'Schema Type',
      'Required Properties',
      'Entity Connected',
      'FAQ Included',
      'LocalBusiness Included',
      'Service Included',
      'Breadcrumb Included',
      'Review Included',
      'Implementation Notes',
      'Priority',
    ],
    minRows: 10,
  },
  {
    name: 'GBP Optimization',
    columns: [
      'GBP Element',
      'Current Status',
      'Recommendation',
      'Category',
      'Service',
      'Description',
      'Photo Type',
      'Post Idea',
      'Q&A',
      'Review Prompt',
      'Local Signal',
      'Priority',
      'Notes',
    ],
    minRows: 10,
  },
  {
    name: 'Review Strategy',
    columns: [
      'Review Source',
      'Review Prompt',
      'Target Service',
      'Target Location',
      'Timing',
      'Automation Trigger',
      'Follow-Up Message',
      'Owner',
      'Priority',
      'Status',
    ],
    minRows: 5,
  },
  {
    name: 'Citation Strategy',
    columns: ['Citation Source', 'URL', 'Category', 'NAP Needed', 'Market', 'Priority', 'Status', 'Notes'],
    minRows: 8,
  },
  {
    name: 'Backlink Strategy',
    columns: [
      'Link Opportunity',
      'Source Type',
      'URL',
      'Market',
      'Relevance',
      'Authority Estimate',
      'Outreach Angle',
      'Anchor Text',
      'Target Page',
      'Risk Level',
      'Priority',
      'Status',
    ],
    minRows: 8,
  },
  {
    name: 'Google Ads Alignment',
    columns: [
      'Campaign',
      'Ad Group',
      'Keyword',
      'Match Type',
      'Intent',
      'Landing Page',
      'CTA',
      'Negative Keywords',
      'Headline Ideas',
      'Description Ideas',
      'Conversion Action',
      'SEO Alignment',
      'Priority',
    ],
    minRows: 10,
  },
  {
    name: 'CRO Strategy',
    columns: [
      'Page',
      'Conversion Goal',
      'Above Fold Recommendation',
      'CTA',
      'Form Fields',
      'Trust Signal',
      'Review Placement',
      'Phone CTA',
      'Objection Handling',
      'Offer',
      'Priority',
      'Notes',
    ],
    minRows: 5,
  },
  {
    name: 'Content Briefs',
    columns: [
      'Page/Article',
      'Target Keyword',
      'Search Intent',
      'Word Count',
      'H1',
      'H2s',
      'H3s',
      'Entities',
      'FAQs',
      'Internal Links',
      'Schema',
      'CTA',
      'Unique Information Gain',
      'Notes',
    ],
    minRows: 5,
  },
  {
    name: 'Programmatic SEO Plan',
    columns: [
      'Template Type',
      'Variable',
      'Example URL',
      'Target Keyword Pattern',
      'Required Unique Content',
      'Risk Level',
      'Internal Links',
      'Schema',
      'QA Requirement',
      'Priority',
    ],
    minRows: 5,
  },
  {
    name: 'Technical SEO Checklist',
    columns: ['Category', 'Issue', 'URL', 'Current Status', 'Impact', 'Fix', 'Priority', 'Developer Notes', 'QA Status'],
    minRows: 10,
  },
  {
    name: 'KPI Dashboard',
    columns: ['KPI', 'Baseline', 'Target Month 1', 'Target Month 2', 'Target Month 3', 'Current', 'Change', 'Status', 'Notes'],
    minRows: 16,
  },
  {
    name: '30-60-90 Roadmap',
    columns: [
      'Phase',
      'Task',
      'Category',
      'Agent Owner',
      'Priority',
      'Expected Impact',
      'Dependency',
      'Due Date',
      'Status',
      'Notes',
    ],
    minRows: 15,
  },
  {
    name: 'Implementation Tracker',
    columns: [
      'Task ID',
      'Task',
      'Category',
      'Owner',
      'Agent',
      'Priority',
      'Status',
      'Start Date',
      'Due Date',
      'Completion %',
      'QA Status',
      'Published URL',
      'Indexed?',
      'GSC Checked?',
      'Notes',
    ],
    minRows: 15,
  },
  {
    name: 'Cost Dashboard',
    columns: ['Market', 'Task Type', 'Quantity', 'Unit Cost', 'Estimated Cost', 'Priority', 'Phase', 'Notes'],
    minRows: 8,
  },
  {
    name: 'Final QA Score',
    columns: ['Category', 'Max Points', 'Score', 'Notes', 'Improvement Needed'],
    minRows: 14,
  },
];

export const LOCATION_TAB_COLUMNS = [
  'Keyword',
  'Keyword Type',
  'Service',
  'Location',
  'Search Intent',
  'Page Mapping',
  'Priority Score',
  'Validation Status',
  'Notes',
];

export const STANDARD_KPIS = [
  'Organic Traffic',
  'Organic Keywords',
  'Top 3 Keywords',
  'Top 10 Keywords',
  'Top 20 Keywords',
  'GBP Calls',
  'GBP Website Clicks',
  'GBP Direction Requests',
  'Form Leads',
  'Phone Calls',
  'Backlinks',
  'Referring Domains',
  'Pages Published',
  'Pages Indexed',
  'Average Position',
  'Conversion Rate',
];

export function getTabSpec(name: string): WorkbookTabSpec | undefined {
  return VF_WORKBOOK_TABS.find((t) => t.name === name);
}

export function sanitizeSheetName(name: string): string {
  return name.replace(/[\\/*?:[\]]/g, '').slice(0, 31);
}

export function locationTabName(market: string): string {
  return sanitizeSheetName(`Loc - ${market}`);
}
